
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";

const getAIClient = () => {
  return new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
};

/**
 * Extracts the first image part from a Gemini response.
 */
const extractImageFromResponse = (response: GenerateContentResponse): string | null => {
  const candidate = response.candidates?.[0];
  if (!candidate || !candidate.content || !candidate.content.parts) return null;

  for (const part of candidate.content.parts) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
    }
  }
  return null;
};

/**
 * Generates a mockup by placing a logo on a product template.
 */
export const generateMockup = async (
  logoBase64: string,
  templateImageUrl: string,
  templateName: string
): Promise<string> => {
  const ai = getAIClient();
  
  // Clean base64 strings if they have prefixes
  const cleanLogo = logoBase64.split(',')[1] || logoBase64;
  
  // Fetch template image and convert to base64
  const templateResponse = await fetch(templateImageUrl);
  const templateBlob = await templateResponse.blob();
  const templateBase64 = await blobToBase64(templateBlob);
  const cleanTemplate = templateBase64.split(',')[1] || templateBase64;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            mimeType: 'image/png',
            data: cleanTemplate,
          },
        },
        {
          inlineData: {
            mimeType: 'image/png',
            data: cleanLogo,
          },
        },
        {
          text: `Please place the provided logo onto the ${templateName} product image. Ensure the logo is placed naturally, following the fabric wrinkles or surface curves. The output should look like a professional product mockup for an e-commerce site. Return only the final image.`,
        },
      ],
    },
  });

  const resultImage = extractImageFromResponse(response);
  if (!resultImage) throw new Error("No image generated by AI.");
  return resultImage;
};

/**
 * Edits an existing mockup based on a text prompt.
 */
export const editMockup = async (
  currentImageBase64: string,
  prompt: string
): Promise<string> => {
  const ai = getAIClient();
  const cleanImage = currentImageBase64.split(',')[1] || currentImageBase64;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            mimeType: 'image/png',
            data: cleanImage,
          },
        },
        {
          text: `Edit this product mockup image according to the following instruction: "${prompt}". Maintain the integrity of the logo placement while applying the requested changes. Return only the edited image.`,
        },
      ],
    },
  });

  const resultImage = extractImageFromResponse(response);
  if (!resultImage) throw new Error("No edited image generated by AI.");
  return resultImage;
};

// Helper to convert blob to base64
const blobToBase64 = (blob: Blob): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
};
